### PR TITLE
Update CI to upload binary packages

### PR DESCRIPTION
**Pull request by gvanuxem**
Upload binaries such that it is available in the CIs Actions pages.
See for example, at the bottom of the page, https://github.com/fricas/fricas/actions/runs/12276733678

Feel free to upload only one package, here it uploads a zip file that contains the .tar.gz and .deb files.

### CODE REVIEW

**Comment by pbroadbery** [comment]
Looks ok - will merge if you're happy with the build result.

**Comment by gvanuxem** [comment]
It works successfully, see here:
https://github.com/gvanuxem/aldor/actions/runs/12305320663/job/34344638642

The commit above is just adding a status badge to README.md. In fact I need
an aldor binary on the Web to add Aldor to another CI for jlFriCAS, FriCAS
with a minimal interface to Julia. And Aldor in jlFriCAS allowed me to find
some issues not rejected by FriCAS. I was using a different scheme for
SquareMatrices (via the use of SubDomain) but this was not consistent so I
reverted my code.

So Ok. But if you only want the tarball in the zip file it doesn't matter
for me. One of the advantages of this PR is to be able to quickly download
a checked Aldor binary.

Greg

Le jeu. 12 déc. 2024 à 23:40, pbroadbery ***@***.***> a
écrit :

**Comment by gvanuxem** [comment]
Just a precision, if I upload a .deb file and a tarball it is because the
.deb file will likely not be installable in a CI since /usr/ is read only
in Ci-s, at least on macOS. But I can install the tarball in /usr/local if
that is the case.

Le jeu. 12 déc. 2024 à 23:55, Grégory Vanuxem ***@***.***> a
écrit :

**Comment by gvanuxem** [comment]
Here you can download the zip file at the bottom of the page (ci-upload
branch):
https://github.com/gvanuxem/aldor/actions/runs/12306399409

Greg

Le ven. 13 déc. 2024 à 00:00, Grégory Vanuxem ***@***.***> a
écrit :

**Comment by pbroadbery** [comment]
Merged - Exporting the artifacts is a good idea, and reminds me that the deb version ought to be changed.  

Separately, I need to look into jFricas sometime...

**Pull request merged**
